export const QUERY_KEYS = {
    HOMEPAGE: ['homepage'],
    PROFILE: ['profile'],
    RIASEC_PROFILE: ['riasec', 'profile'],
    RIASEC_HISTORY: ['riasec', 'history'],
    RIASEC_QUESTIONS: ['riasec', 'questions'],
    PROGRAMS: ['programs'],
    PROGRAM_DETAIL: ['program', 'detail'],
    SAVED_PROGRAMS: ['saved-programs'],
    MATCHING_LATEST: ['matching', 'latest'],
    MATCHING_HISTORY: ['matching', 'history'],
    MATCHING_RUN: ['matching', 'run'],
    ADMIN_STATS: ['admin', 'stats'],
    ADMIN_USERS: ['admin', 'users'],
    ADMIN_UNIVERSITIES: ['admin', 'universities'],
    ADMIN_PROGRAMS: ['admin', 'programs'],
    ADMIN_QUESTION_BANKS: ['admin', 'question-banks'],
    ADMIN_QUESTIONS: ['admin', 'questions'],
    ADMIN_EVALUATION: ['admin', 'evaluation'],
    ADMIN_FEEDBACK_STATS: ['admin', 'feedback-stats'],
};
