export const FOCUS_AREA_OPTIONS = [
    { value: 'Computer Science', label: 'Computer Science' },
    { value: 'Software Engineering', label: 'Software Engineering' },
    { value: 'Information Technology', label: 'Information Technology' },
    { value: 'Information Systems', label: 'Information Systems' },
    { value: 'Data Science', label: 'Data Science' },
    { value: 'Data Science and AI', label: 'Data Science and AI' },
    { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'Computer Networking', label: 'Computer Networking' },
    { value: 'Machine Learning and Computer Engineering', label: 'Machine Learning and Computer Engineering' },
    { value: 'Information and Communication Technology', label: 'Information and Communication Technology' },
    { value: 'Global Software Engineering and ICT', label: 'Global Software Engineering and ICT' },
    { value: 'Multimedia and Design', label: 'Multimedia and Design' },
    { value: 'Game Development', label: 'Game Development' },
    { value: 'E-Commerce', label: 'E-Commerce' },
    { value: 'Electrical Engineering', label: 'Electrical Engineering' },
    { value: 'Electrical and Information Engineering', label: 'Electrical and Information Engineering' },
    { value: 'Electronics and Telecommunications', label: 'Electronics and Telecommunications' },
    { value: 'Mechanical Engineering', label: 'Mechanical Engineering' },
    { value: 'Mechatronics', label: 'Mechatronics' },
    { value: 'Civil Engineering', label: 'Civil Engineering' },
    { value: 'Chemical Engineering', label: 'Chemical Engineering' },
    { value: 'Environmental Engineering', label: 'Environmental Engineering' },
    { value: 'Aerospace Engineering', label: 'Aerospace Engineering' },
    { value: 'Space Engineering', label: 'Space Engineering' },
    { value: 'Biomedical Engineering', label: 'Biomedical Engineering' },
    { value: 'Industrial and Systems Engineering', label: 'Industrial and Systems Engineering' },
    { value: 'Industrial Maintenance', label: 'Industrial Maintenance' },
    { value: 'Control and Automation Engineering', label: 'Control and Automation Engineering' },
    { value: 'Robotics and Automation', label: 'Robotics and Automation' },
    { value: 'Hardware and Systems', label: 'Hardware and Systems' },
    { value: 'Semiconductor Engineering', label: 'Semiconductor Engineering' },
    { value: 'Nuclear Engineering', label: 'Nuclear Engineering' },
    { value: 'Petroleum Engineering', label: 'Petroleum Engineering' },
    { value: 'Construction Management', label: 'Construction Management' },
    { value: 'Transportation Engineering', label: 'Transportation Engineering' },
    { value: 'Materials Science', label: 'Materials Science' },
    { value: 'Business Administration', label: 'Business Administration' },
    { value: 'Finance and Banking', label: 'Finance and Banking' },
    { value: 'Accounting', label: 'Accounting' },
    { value: 'Accounting and Auditing', label: 'Accounting and Auditing' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Economics', label: 'Economics' },
    { value: 'Logistics and Supply Chain Management', label: 'Logistics and Supply Chain Management' },
    { value: 'International Business', label: 'International Business' },
    { value: 'Human Resource Management', label: 'Human Resource Management' },
    { value: 'Tourism Management', label: 'Tourism Management' },
    { value: 'Tourism and Hospitality', label: 'Tourism and Hospitality' },
    { value: 'Real Estate', label: 'Real Estate' },
    { value: 'Auditing', label: 'Auditing' },
    { value: 'Mathematics', label: 'Mathematics' },
    { value: 'Applied Mathematics and Quantitative Finance', label: 'Applied Mathematics and Quantitative Finance' },
    { value: 'Statistics and Data Analytics', label: 'Statistics and Data Analytics' },
    { value: 'Physics', label: 'Physics' },
    { value: 'Chemistry', label: 'Chemistry' },
    { value: 'Chemistry - Biochemistry', label: 'Chemistry - Biochemistry' },
    { value: 'Biology and Biotechnology', label: 'Biology and Biotechnology' },
    { value: 'Biotechnology', label: 'Biotechnology' },
    { value: 'Food Technology', label: 'Food Technology' },
    { value: 'Environmental Science', label: 'Environmental Science' },
    { value: 'Geology', label: 'Geology' },
    { value: 'Agriculture', label: 'Agriculture' },
    { value: 'Medicine', label: 'Medicine' },
    { value: 'Pharmacy', label: 'Pharmacy' },
    { value: 'Nursing', label: 'Nursing' },
    { value: 'Public Health', label: 'Public Health' },
    { value: 'English Language', label: 'English Language' },
    { value: 'Korean Language', label: 'Korean Language' },
    { value: 'Japanese Language', label: 'Japanese Language' },
    { value: 'Chinese Language', label: 'Chinese Language' },
    { value: 'French Language', label: 'French Language' },
    { value: 'Foreign Languages', label: 'Foreign Languages' },
    { value: 'Literature', label: 'Literature' },
    { value: 'History', label: 'History' },
    { value: 'Philosophy', label: 'Philosophy' },
    { value: 'Psychology', label: 'Psychology' },
    { value: 'Sociology', label: 'Sociology' },
    { value: 'Education', label: 'Education' },
    { value: 'Journalism', label: 'Journalism' },
    { value: 'Journalism and Communications', label: 'Journalism and Communications' },
    { value: 'International Relations', label: 'International Relations' },
    { value: 'Social Work', label: 'Social Work' },
    { value: 'Law', label: 'Law' },
    { value: 'International Law', label: 'International Law' },
    { value: 'Architecture', label: 'Architecture' },
    { value: 'Graphic Design', label: 'Graphic Design' },
    { value: 'Fine Arts', label: 'Fine Arts' },
    { value: 'Music', label: 'Music' },
    { value: 'Film and Media', label: 'Film and Media' },
    { value: 'Fashion and Garment Technology', label: 'Fashion and Garment Technology' },
];
