const DEFAULT_ASSESSMENT_VERSION = 2;
const REQUIRED_QUESTION_COUNT = 48;
const REQUIRED_PER_DIMENSION = 8;
const RIASEC_DIMENSIONS = ['R', 'I', 'A', 'S', 'E', 'C'];
const RESERVED_LEGACY_VERSIONS = [1, 2, 3, 4];

const QUESTION_BANK_STATUS = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    ARCHIVED: 'ARCHIVED',
};

module.exports = {
    DEFAULT_ASSESSMENT_VERSION,
    REQUIRED_QUESTION_COUNT,
    REQUIRED_PER_DIMENSION,
    RESERVED_LEGACY_VERSIONS,
    RIASEC_DIMENSIONS,
    QUESTION_BANK_STATUS,
};
